openapi: 3.1.0
info:
  title: Cerberix Worker API
  version: 0.1.0
  description: API for event ingestion, delivery replay, and health.
servers:
  - url: http://localhost:4001
    description: Local worker
security:
  - ProjectAuth: []
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
  /api/v1/events:
    post:
      summary: Ingest event
      description: Publish an event to Cerberix for a project.
      security:
        - ProjectAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventIngestRequest'
      responses:
        '200':
          description: Queued
          content:
            application/json:
              schema:
                type: object
                properties:
                  eventId:
                    type: string
                  queuedDeliveriesCount:
                    type: integer
        '401':
          description: Unauthorized
        '429':
          description: Rate limited or monthly limit exceeded
  /api/v1/deliveries/{id}/replay:
    post:
      summary: Replay delivery
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Replay queued
          content:
            application/json:
              schema:
                type: object
                properties:
                  deliveryId:
                    type: string
        '404':
          description: Not found
components:
  securitySchemes:
    ProjectAuth:
      type: http
      scheme: bearer
      bearerFormat: Project secret in Authorization header ("Bearer <secret>")
  schemas:
    EventIngestRequest:
      type: object
      required: [type, payload]
      properties:
        type:
          type: string
        payload:
          type: object
          additionalProperties: true
        idempotencyKey:
          type: string
        metadata:
          type: object
          additionalProperties: true

